os: linux
dist: xenial
language: node_js
node_js: lts/*
addons:
  chrome: stable

env:
  global:
    - NODE_ENV=production

install:
  - npm ci --production=false
  - cd tests
  - npm ci --production=false
  - cd ..
  - npm run setup

jobs:
  include:
    - stage: test
      script: npm run quality:check
    - script:
        - npm run build
        - npm test

deploy:
  edge: true
  provider: npm
  email: tylergrinn@gmail.com
  api_token:
    secure: z+7dzS7J8IWByzG/j7HQDXtGU8HONRQ9/uAN8r43/e8PxoGAwJd3IxyKefUUaPtA3wcHHhYu0fahdM8gl0QVWaVge2LNun1BZtLL8vAIieH2ySLbGZsqsxeIv9WAJId0WPuFcUd5wyoR6HqvDN2VSlKpPtE4RFOWv9OaZBsWERuIjg55ItWbHFUSbghKlZkyA9oeu2mBLZ5v4vJrdqoXpV1L54WRhSOEgfcWSi3sYmX45As39xF8s3yxXRf5vF2XcLi1/Svc1Q0lFVQWNntVWqP3caCqcQtKnLfSes+mSWN7lFxytrHYsR/fT3ZHefxB3JhAjTzsTpHRNd2hNugRKD4jg+uaK5OB7YhV2RmEeg+kA+HNDwsxrb85Q54CMw+b3QwdhvcKlsozJPhcqpLuMbem9bLVVcVvj1lQ+Qe4uhN3WQXfjq+TDrQYlkwn3/GGgztpRoC48u6pCrW1ZqD2OYF/ZNNCHdpKKJJ26jsaJEpM/0Gou8s3mWEb2TbNlL5qGST74HLDDGl3TCInffQBHpN/J0t+uHD3qhmnyi+Kl8eYBH6DwIxLiWPY/hl/N9QqrpmNI6LNxjeZtsEORzvvncT/W9aDARsxHttDrqGhd+n28o8CplFBa4bfOX5m1k1d0P+XdN/ZK1NPKQigEwNMSUPthhvj+e5X/YivUUwfVPc=
  on:
    branch: master
    tags: true

after_deploy:
  - npm run setup:prod
  - npm run build
  - npm test
